require("dotenv/config");

const fs = require("node:fs");
const path = require("node:path");

const ROOT_DIR = __dirname;
const DATA_DIR = path.join(ROOT_DIR, "game-data");
const SQLITE_DATABASE_PATH = process.env.SQLITE_DATABASE_PATH || path.join(DATA_DIR, "abo-life.sqlite");

const SQLITE_SCHEMA = `
  PRAGMA foreign_keys = ON;
  PRAGMA journal_mode = WAL;

  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'player',
    display_name TEXT NOT NULL,
    archive_name TEXT NOT NULL DEFAULT '',
    archive_note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS saves (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    slot INTEGER NOT NULL,
    archive_id TEXT NOT NULL,
    age INTEGER NOT NULL,
    quarter INTEGER NOT NULL,
    deceased INTEGER NOT NULL DEFAULT 0,
    saved_at TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    UNIQUE (user_id, slot),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  );
`;

const POSTGRES_SCHEMA = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'player',
    display_name TEXT NOT NULL,
    archive_name TEXT NOT NULL DEFAULT '',
    archive_note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS saves (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slot INTEGER NOT NULL,
    archive_id TEXT NOT NULL,
    age INTEGER NOT NULL,
    quarter INTEGER NOT NULL,
    deceased BOOLEAN NOT NULL DEFAULT FALSE,
    saved_at TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    UNIQUE (user_id, slot)
  );
`;

function createPostgresPool() {
  const { Pool } = require("pg");
  const connectionString = process.env.DATABASE_URL;
  const poolConfig = { connectionString };
  const urlHasSslConfig = /[?&]ssl(mode|cert|key|rootcert)=/i.test(connectionString);
  const envHasSslConfig = Boolean(
    process.env.PGSSLMODE ||
    process.env.PGSSLROOTCERT ||
    process.env.PGSSLCERT ||
    process.env.PGSSLKEY
  );

  if (process.env.DATABASE_SSL === "false") {
    poolConfig.ssl = false;
  } else if (process.env.DATABASE_SSL_REJECT_UNAUTHORIZED === "true") {
    poolConfig.ssl = { rejectUnauthorized: true };
  } else if (!urlHasSslConfig && !envHasSslConfig) {
    poolConfig.ssl = { rejectUnauthorized: false };
  }

  const pool = new Pool(poolConfig);
  pool.on("error", (error) => {
    console.error("[ABO Storage] idle Postgres client error", error);
  });
  return pool;
}

class SqliteStore {
  constructor(databasePath = SQLITE_DATABASE_PATH) {
    this.mode = "sqlite";
    this.databasePath = databasePath;
    this.db = null;
    this.statements = null;
  }

  async init() {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    const { DatabaseSync } = require("node:sqlite");
    this.db = new DatabaseSync(this.databasePath);
    this.db.exec(SQLITE_SCHEMA);
    this.statements = {
      findUserByUsername: this.db.prepare(`
        SELECT id, username, password_hash, role, display_name, archive_name, archive_note, created_at
        FROM users
        WHERE username = ?
      `),
      findAdminUser: this.db.prepare(`
        SELECT id, username FROM users WHERE role = 'admin' LIMIT 1
      `),
      insertUser: this.db.prepare(`
        INSERT INTO users (username, password_hash, role, display_name, archive_name, archive_note, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
      `),
      updateAdminUser: this.db.prepare(`
        UPDATE users
        SET username = ?,
            password_hash = ?,
            role = 'admin',
            display_name = ?,
            archive_name = ?,
            archive_note = ?
        WHERE id = ?
      `),
      insertSession: this.db.prepare(`
        INSERT INTO sessions (user_id, token_hash, expires_at, created_at)
        VALUES (?, ?, ?, ?)
      `),
      findSessionUser: this.db.prepare(`
        SELECT users.id, users.username, users.role, users.display_name, users.archive_name, users.archive_note, sessions.token_hash, sessions.expires_at
        FROM sessions
        JOIN users ON users.id = sessions.user_id
        WHERE sessions.token_hash = ? AND sessions.expires_at > ?
        LIMIT 1
      `),
      deleteSessionByHash: this.db.prepare(`
        DELETE FROM sessions WHERE token_hash = ?
      `),
      deleteExpiredSessions: this.db.prepare(`
        DELETE FROM sessions WHERE expires_at <= ?
      `),
      listSavesByUserId: this.db.prepare(`
        SELECT slot, archive_id, age, quarter, deceased, saved_at
        FROM saves
        WHERE user_id = ?
        ORDER BY slot ASC
      `),
      findSaveByUserAndSlot: this.db.prepare(`
        SELECT slot, archive_id, age, quarter, deceased, saved_at, payload_json
        FROM saves
        WHERE user_id = ? AND slot = ?
        LIMIT 1
      `),
      upsertSave: this.db.prepare(`
        INSERT INTO saves (user_id, slot, archive_id, age, quarter, deceased, saved_at, payload_json)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(user_id, slot) DO UPDATE SET
          archive_id = excluded.archive_id,
          age = excluded.age,
          quarter = excluded.quarter,
          deceased = excluded.deceased,
          saved_at = excluded.saved_at,
          payload_json = excluded.payload_json
      `),
      listUsersWithSaves: this.db.prepare(`
        SELECT
          users.id,
          users.username,
          users.role,
          users.display_name,
          users.archive_name,
          users.archive_note,
          users.created_at,
          saves.slot,
          saves.archive_id,
          saves.age,
          saves.quarter,
          saves.deceased,
          saves.saved_at
        FROM users
        LEFT JOIN saves ON saves.user_id = users.id
        ORDER BY users.created_at DESC, saves.slot ASC
      `)
    };
  }

  async findUserByUsername(username) {
    return this.statements.findUserByUsername.get(username) || null;
  }

  async findAdminUser() {
    return this.statements.findAdminUser.get() || null;
  }

  async insertUser(user) {
    const result = this.statements.insertUser.run(
      user.username,
      user.passwordHash,
      user.role,
      user.displayName,
      user.archiveName,
      user.archiveNote,
      user.createdAt
    );
    return Number(result.lastInsertRowid);
  }

  async updateAdminUser(userId, user) {
    this.statements.updateAdminUser.run(
      user.username,
      user.passwordHash,
      user.displayName,
      user.archiveName,
      user.archiveNote,
      userId
    );
  }

  async insertSession(userId, tokenHash, expiresAt, createdAt) {
    this.statements.insertSession.run(userId, tokenHash, expiresAt, createdAt);
  }

  async findSessionUser(tokenHash, currentTime) {
    return this.statements.findSessionUser.get(tokenHash, currentTime) || null;
  }

  async deleteSessionByHash(tokenHash) {
    this.statements.deleteSessionByHash.run(tokenHash);
  }

  async deleteExpiredSessions(currentTime) {
    this.statements.deleteExpiredSessions.run(currentTime);
  }

  async listSavesByUserId(userId) {
    return this.statements.listSavesByUserId.all(userId);
  }

  async findSaveByUserAndSlot(userId, slot) {
    return this.statements.findSaveByUserAndSlot.get(userId, slot) || null;
  }

  async upsertSave(userId, slot, meta, savedAt, payloadJson) {
    this.statements.upsertSave.run(
      userId,
      slot,
      meta.archiveId,
      meta.age,
      meta.quarter,
      meta.deceased ? 1 : 0,
      savedAt,
      payloadJson
    );
  }

  async listUsersWithSaves() {
    return this.statements.listUsersWithSaves.all();
  }
}

class PostgresStore {
  constructor(pool) {
    this.mode = "postgres";
    this.pool = pool;
  }

  async init() {
    await this.pool.query(POSTGRES_SCHEMA);
  }

  async findUserByUsername(username) {
    const { rows } = await this.pool.query(`
      SELECT id, username, password_hash, role, display_name, archive_name, archive_note, created_at
      FROM users
      WHERE username = $1
    `, [username]);
    return rows[0] || null;
  }

  async findAdminUser() {
    const { rows } = await this.pool.query(`
      SELECT id, username FROM users WHERE role = 'admin' LIMIT 1
    `);
    return rows[0] || null;
  }

  async insertUser(user) {
    const { rows } = await this.pool.query(`
      INSERT INTO users (username, password_hash, role, display_name, archive_name, archive_note, created_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7)
      RETURNING id
    `, [
      user.username,
      user.passwordHash,
      user.role,
      user.displayName,
      user.archiveName,
      user.archiveNote,
      user.createdAt
    ]);
    return rows[0].id;
  }

  async updateAdminUser(userId, user) {
    await this.pool.query(`
      UPDATE users
      SET username = $1,
          password_hash = $2,
          role = 'admin',
          display_name = $3,
          archive_name = $4,
          archive_note = $5
      WHERE id = $6
    `, [
      user.username,
      user.passwordHash,
      user.displayName,
      user.archiveName,
      user.archiveNote,
      userId
    ]);
  }

  async insertSession(userId, tokenHash, expiresAt, createdAt) {
    await this.pool.query(`
      INSERT INTO sessions (user_id, token_hash, expires_at, created_at)
      VALUES ($1, $2, $3, $4)
    `, [userId, tokenHash, expiresAt, createdAt]);
  }

  async findSessionUser(tokenHash, currentTime) {
    const { rows } = await this.pool.query(`
      SELECT users.id, users.username, users.role, users.display_name, users.archive_name, users.archive_note, sessions.token_hash, sessions.expires_at
      FROM sessions
      JOIN users ON users.id = sessions.user_id
      WHERE sessions.token_hash = $1 AND sessions.expires_at > $2
      LIMIT 1
    `, [tokenHash, currentTime]);
    return rows[0] || null;
  }

  async deleteSessionByHash(tokenHash) {
    await this.pool.query(`DELETE FROM sessions WHERE token_hash = $1`, [tokenHash]);
  }

  async deleteExpiredSessions(currentTime) {
    await this.pool.query(`DELETE FROM sessions WHERE expires_at <= $1`, [currentTime]);
  }

  async listSavesByUserId(userId) {
    const { rows } = await this.pool.query(`
      SELECT slot, archive_id, age, quarter, deceased, saved_at
      FROM saves
      WHERE user_id = $1
      ORDER BY slot ASC
    `, [userId]);
    return rows;
  }

  async findSaveByUserAndSlot(userId, slot) {
    const { rows } = await this.pool.query(`
      SELECT slot, archive_id, age, quarter, deceased, saved_at, payload_json
      FROM saves
      WHERE user_id = $1 AND slot = $2
      LIMIT 1
    `, [userId, slot]);
    return rows[0] || null;
  }

  async upsertSave(userId, slot, meta, savedAt, payloadJson) {
    await this.pool.query(`
      INSERT INTO saves (user_id, slot, archive_id, age, quarter, deceased, saved_at, payload_json)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      ON CONFLICT(user_id, slot) DO UPDATE SET
        archive_id = excluded.archive_id,
        age = excluded.age,
        quarter = excluded.quarter,
        deceased = excluded.deceased,
        saved_at = excluded.saved_at,
        payload_json = excluded.payload_json
    `, [
      userId,
      slot,
      meta.archiveId,
      meta.age,
      meta.quarter,
      meta.deceased,
      savedAt,
      payloadJson
    ]);
  }

  async listUsersWithSaves() {
    const { rows } = await this.pool.query(`
      SELECT
        users.id,
        users.username,
        users.role,
        users.display_name,
        users.archive_name,
        users.archive_note,
        users.created_at,
        saves.slot,
        saves.archive_id,
        saves.age,
        saves.quarter,
        saves.deceased,
        saves.saved_at
      FROM users
      LEFT JOIN saves ON saves.user_id = users.id
      ORDER BY users.created_at DESC, saves.slot ASC
    `);
    return rows;
  }
}

async function createStore() {
  if (process.env.DATABASE_URL) {
    const store = new PostgresStore(createPostgresPool());
    await store.init();
    return store;
  }

  const store = new SqliteStore();
  await store.init();
  return store;
}

module.exports = {
  createPostgresPool,
  createStore,
  POSTGRES_SCHEMA,
  SQLITE_DATABASE_PATH,
  SqliteStore
};
